import { ArrowUpRight, Check, Compass, Globe2, Menu, Plus, Sparkles, Users } from 'lucide-react'
export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-brand text-brand-foreground"><Compass size={18} /></div><span className="text-lg font-semibold tracking-tight">summer</span></div>
        <nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#how">How it works</a><a href="#values">Why Summer</a><a href="#workspace">Workspace</a></nav>
        <div className="flex items-center gap-3"><button className="hidden rounded-full px-4 py-2 text-sm font-medium text-muted-foreground md:block">Log in</button><button className="rounded-full bg-foreground px-5 py-2.5 text-sm font-semibold text-background">Get started <ArrowUpRight className="ml-1 inline" size={15} /></button><Menu className="md:hidden" size={20} /></div>
      </header>
      <section className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-28 lg:pt-24">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-semibold text-brand"><Sparkles size={13} /> Made for the people you travel with</div><h1 className="max-w-xl text-balance text-5xl font-semibold leading-[1.03] tracking-[-0.06em] sm:text-7xl">Make room for the <span className="text-brand">good stuff.</span></h1><p className="mt-7 max-w-lg text-pretty text-lg leading-8 text-muted-foreground">Summer is a shared travel workspace for the trips you talk about all year. Plan less. Go further. Remember everything.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#workspace" className="rounded-full bg-brand px-6 py-3.5 text-sm font-semibold text-brand-foreground">Plan a trip <ArrowUpRight className="ml-1 inline" size={16} /></a><a href="#how" className="rounded-full border border-border bg-card px-6 py-3.5 text-sm font-semibold">See how it works</a></div><div className="mt-10 flex items-center gap-3 text-sm text-muted-foreground"><div className="flex -space-x-2"><span className="flex size-8 items-center justify-center rounded-full border-2 border-background bg-[#d9a17b] text-xs">A</span><span className="flex size-8 items-center justify-center rounded-full border-2 border-background bg-[#739b8a] text-xs">J</span><span className="flex size-8 items-center justify-center rounded-full border-2 border-background bg-[#dbbf78] text-xs">M</span></div><span>Built for groups of 2 to 12</span></div></div>
        <div className="relative"><div className="overflow-hidden rounded-[2rem] bg-brand p-3 shadow-2xl shadow-brand/15"><div className="relative h-[420px] overflow-hidden rounded-[1.5rem] bg-[#d9e1d4] p-6"><div className="absolute inset-0 opacity-70" style={{backgroundImage:'linear-gradient(135deg, transparent 35%, rgba(30,101,88,.2) 35%, rgba(30,101,88,.2) 36%, transparent 36%), linear-gradient(45deg, transparent 60%, rgba(215,138,74,.25) 60%, rgba(215,138,74,.25) 61%, transparent 61%)'}} /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand/70">Trip workspace</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Dakar, slowly.</h2></div><div className="rounded-full bg-card/80 p-3"><Globe2 className="text-brand" size={20} /></div></div><div className="rounded-2xl border border-white/60 bg-card/90 p-5 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Next adventure</p><p className="mt-1 font-semibold">15 — 22 Aug 2025</p></div><div className="rounded-full bg-accent/15 px-3 py-1 text-xs font-semibold text-accent">Planning</div></div><div className="mt-5 h-2 rounded-full bg-muted"><div className="h-2 w-2/5 rounded-full bg-accent" /></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>4 of 10 things ready</span><span>$2,840 / $6,000</span></div></div></div></div></div><div className="absolute -bottom-5 -left-5 rounded-2xl border border-border bg-card p-4 shadow-xl"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-accent/15 text-accent"><Users size={17} /></div><div><p className="text-xs text-muted-foreground">Your people are in</p><p className="text-sm font-semibold">4 friends joined</p></div></div></div></div>
      </section>
      <section id="values" className="border-y border-border bg-card"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-12 md:grid-cols-3 lg:px-10"><div><p className="text-sm font-semibold text-brand">01</p><h3 className="mt-3 text-xl font-semibold">One place, no noise.</h3><p className="mt-2 leading-6 text-muted-foreground">Ideas, bookings, budgets, and memories — together, without the spreadsheet chaos.</p></div><div><p className="text-sm font-semibold text-brand">02</p><h3 className="mt-3 text-xl font-semibold">Everyone has a say.</h3><p className="mt-2 leading-6 text-muted-foreground">Make decisions as a group, keep the conversation moving, and never lose the good idea.</p></div><div><p className="text-sm font-semibold text-brand">03</p><h3 className="mt-3 text-xl font-semibold">Go at your own pace.</h3><p className="mt-2 leading-6 text-muted-foreground">A flexible plan is a better plan. Leave room for the unexpected.</p></div></div></section>
      <section id="workspace" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="rounded-[2rem] border border-border bg-card p-8 md:p-12"><p className="text-sm font-semibold text-brand">Your trip, your pace.</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight md:text-4xl">Start with a shared workspace built for the people going.</h2><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Create an account to bring your itinerary, budget, saved places, and travel crew into one calm place.</p><a href="/sign-up" className="mt-7 inline-flex rounded-full bg-brand px-6 py-3.5 text-sm font-semibold text-brand-foreground">Create your workspace <ArrowUpRight className="ml-1" size={16} /></a></div></section>
      <footer className="border-t border-border px-6 py-8 text-sm text-muted-foreground lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 md:flex-row"><span>summer, for everywhere.</span><span>© 2025 Summer Studio</span></div></footer>
    </main>
  )
}
