'use client'

import { useEffect, useState, useTransition } from 'react'
import { addExpense, addMember, createTrip, getTripData, savePlace, seedFirstTrip } from '@/app/actions/trips'
import { CalendarDays, Check, CircleDollarSign, MapPin, Plus, Send, Sparkles, Users } from 'lucide-react'

type Data = Awaited<ReturnType<typeof getTripData>>
type TripInput = { name: string; destination: string; budget: number }
type ExpenseInput = { tripId: string; label: string; amount: number; category: string; payer: string }
type MemberInput = { tripId: string; name: string; email: string }
type PlaceInput = { tripId: string; name: string; city: string; note?: string }

export function Workspace() {
  const [data, setData] = useState<Data>({ trips: [], expenses: [], members: [], places: [], activity: [] })
  const [selected, setSelected] = useState(0)
  const [section, setSection] = useState<'overview' | 'budget' | 'people' | 'places'>('overview')
  const [form, setForm] = useState<'trip' | 'expense' | 'member' | 'place' | null>(null)
  const [isPending, startTransition] = useTransition()
  const trip = data.trips[selected]

  useEffect(() => { startTransition(async () => { await seedFirstTrip(); setData(await getTripData()) }) }, [])
  const refresh = () => startTransition(async () => setData(await getTripData()))
  const submit = (action: () => Promise<unknown>) => { startTransition(async () => { await action(); setForm(null); setData(await getTripData()) }) }
  const spent = data.expenses.reduce((sum, item) => sum + Number(item.amount), 0)
  const budget = Number(trip?.budget ?? 0)

  return <div className="rounded-[2rem] border border-border bg-card p-5 shadow-sm md:p-8">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-brand/10 px-3 py-1.5 text-xs font-semibold text-brand"><Sparkles size={13} /> Your travel desk</div><h2 className="text-3xl font-semibold tracking-tight">Good plans start here.</h2><p className="mt-2 text-muted-foreground">Bring your people in, then let the trip take shape.</p></div><button disabled={isPending} onClick={() => setForm(form === 'trip' ? null : 'trip')} className="rounded-full bg-brand px-5 py-3 text-sm font-semibold text-brand-foreground"><Plus className="mr-1 inline" size={16} /> New trip</button></div>
    {form === 'trip' && <TripForm onSubmit={(v: TripInput) => submit(() => createTrip(v))} />}
    {!trip ? <div className="mt-8 rounded-2xl bg-muted p-8 text-center">Create your first trip to start planning.</div> : <>
      <div className="mt-8 flex flex-wrap gap-2 border-b border-border pb-3">{(['overview', 'budget', 'people', 'places'] as const).map(item => <button key={item} onClick={() => setSection(item)} className={`rounded-full px-4 py-2 text-sm font-semibold capitalize ${section === item ? 'bg-foreground text-background' : 'text-muted-foreground hover:bg-muted'}`}>{item}</button>)}</div>
      <div className="mt-6 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-3">{data.trips.map((item, index) => <button key={item.id} onClick={() => { setSelected(index); setSection('overview') }} className={`w-full rounded-2xl border p-4 text-left transition ${selected === index ? 'border-brand bg-brand/5' : 'border-border bg-background hover:border-brand/40'}`}><div className="flex items-start justify-between"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">{item.destination}</p></div><span className="rounded-full bg-accent/15 px-2.5 py-1 text-xs font-semibold text-accent">{item.status}</span></div><div className="mt-4 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-brand" style={{ width: `${Math.min(100, budget ? spent / budget * 100 : 0)}%` }} /></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{data.places.length + data.members.length} planning items</span><span>${spent.toLocaleString()} / ${budget.toLocaleString()}</span></div></button>)}</div>
      <div className="rounded-2xl bg-muted/60 p-5 md:p-6">{section === 'overview' && <Overview trip={trip} spent={spent} budget={budget} members={data.members.length} places={data.places.length} activity={data.activity} onAction={setForm} />}{section === 'budget' && <Budget expenses={data.expenses} onAction={() => setForm('expense')} />}{section === 'people' && <People members={data.members} onAction={() => setForm('member')} />}{section === 'places' && <Places places={data.places} onAction={() => setForm('place')} />}</div></div>
    </>}
    {form === 'expense' && trip && <ExpenseForm tripId={trip.id} onSubmit={(v: ExpenseInput) => submit(() => addExpense(v))} onClose={() => setForm(null)} />}{form === 'member' && trip && <MemberForm tripId={trip.id} onSubmit={(v: MemberInput) => submit(() => addMember(v))} onClose={() => setForm(null)} />}{form === 'place' && trip && <PlaceForm tripId={trip.id} onSubmit={(v: PlaceInput) => submit(() => savePlace(v))} onClose={() => setForm(null)} />}
    {isPending && <p className="mt-4 text-center text-xs text-muted-foreground">Saving your plans…</p>}
  </div>
}

function Overview({ trip, spent, budget, members, places, activity, onAction }: any) { return <><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Current trip</p><h3 className="mt-2 text-3xl font-semibold tracking-tight">{trip.name}</h3><p className="mt-2 text-muted-foreground">{trip.destination}</p></div><div className="rounded-full bg-brand/10 p-3 text-brand"><MapPin size={20} /></div></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={<CircleDollarSign size={18} />} label="Spent" value={`$${spent.toLocaleString()}`} /><Metric icon={<Users size={18} />} label="Travelers" value={String(members)} /><Metric icon={<MapPin size={18} />} label="Saved places" value={String(places)} /><Metric icon={<CalendarDays size={18} />} label="Budget left" value={`$${Math.max(0, budget - spent).toLocaleString()}`} /></div><div className="mt-7 flex flex-wrap gap-3"><ActionButton icon={<CircleDollarSign size={16} />} label="Add expense" onClick={() => onAction('expense')} /><ActionButton icon={<Users size={16} />} label="Invite someone" onClick={() => onAction('member')} /><ActionButton icon={<MapPin size={16} />} label="Save a place" onClick={() => onAction('place')} /></div><div className="mt-8"><p className="text-sm font-semibold">Recent activity</p><div className="mt-3 space-y-3">{activity.length ? activity.slice(0, 3).map((item: any) => <div key={item.id} className="flex items-center gap-3 text-sm text-muted-foreground"><Check size={15} className="text-brand" />{item.message}</div>) : <p className="text-sm text-muted-foreground">Your trip story will appear here.</p>}</div></div></> }
function Budget({ expenses, onAction }: any) { return <><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Shared budget</p><h3 className="mt-2 text-2xl font-semibold">Every cost, accounted for.</h3></div><button onClick={onAction} className="rounded-full bg-brand px-4 py-2 text-sm font-semibold text-brand-foreground"><Plus className="mr-1 inline" size={15} /> Add</button></div><div className="mt-6 space-y-3">{expenses.length ? expenses.map((item: any) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-border bg-card p-4"><div><p className="font-medium">{item.label}</p><p className="text-xs text-muted-foreground">{item.category} · paid by {item.payer}</p></div><p className="font-semibold">${Number(item.amount).toLocaleString()}</p></div>) : <p className="rounded-xl bg-card p-6 text-sm text-muted-foreground">No expenses yet. Add the first one.</p>}</div></> }
function People({ members, onAction }: any) { return <Panel title="Your people" subtitle="Keep the group in the loop." action="Invite" onAction={onAction}>{members.length ? members.map((m: any) => <div key={m.id} className="flex items-center justify-between rounded-xl bg-card p-4"><div><p className="font-medium">{m.name}</p><p className="text-xs text-muted-foreground">{m.email}</p></div><span className="text-xs text-brand">{m.role}</span></div>) : <p className="text-sm text-muted-foreground">Invite your first travel companion.</p>}</Panel> }
function Places({ places, onAction }: any) { return <Panel title="Saved places" subtitle="A short list beats a long itinerary." action="Save place" onAction={onAction}>{places.length ? places.map((p: any) => <div key={p.id} className="rounded-xl bg-card p-4"><p className="font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{p.city}{p.note ? ` · ${p.note}` : ''}</p></div>) : <p className="text-sm text-muted-foreground">Save a restaurant, beach, gallery, or anything you want to remember.</p>}</Panel> }
function Panel({ title, subtitle, action, onAction, children }: any) { return <><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand">Workspace</p><h3 className="mt-2 text-2xl font-semibold">{title}</h3><p className="mt-1 text-muted-foreground">{subtitle}</p></div><button onClick={onAction} className="rounded-full bg-brand px-4 py-2 text-sm font-semibold text-brand-foreground">{action}</button></div><div className="mt-6 space-y-3">{children}</div></> }
function Metric({ icon, label, value }: any) { return <div className="rounded-xl border border-border bg-card p-3"><div className="text-brand">{icon}</div><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate text-sm font-semibold">{value}</p></div> }
function ActionButton({ icon, label, onClick }: any) { return <button onClick={onClick} className="rounded-xl border border-border bg-card px-4 py-3 text-sm font-semibold hover:border-brand/50">{icon}<span className="ml-2">{label}</span></button> }
function TripForm({ onSubmit }: { onSubmit: (value: TripInput) => void }) { const [name, setName] = useState(''); const [destination, setDestination] = useState(''); const [budget, setBudget] = useState(''); return <form onSubmit={e => { e.preventDefault(); if (name && destination) onSubmit({ name, destination, budget: Number(budget) || 0 }) }} className="mt-6 grid gap-3 rounded-2xl bg-muted p-4 md:grid-cols-[1fr_1fr_160px_auto]"><input value={name} onChange={e => setName(e.target.value)} placeholder="Trip name" required className="field" /><input value={destination} onChange={e => setDestination(e.target.value)} placeholder="Destination + dates" required className="field" /><input value={budget} onChange={e => setBudget(e.target.value)} placeholder="Budget" type="number" min="0" className="field" /><button className="rounded-xl bg-foreground px-5 py-3 text-sm font-semibold text-background">Create</button></form> }
function ExpenseForm({ tripId, onSubmit, onClose }: { tripId: string; onSubmit: (value: ExpenseInput) => void; onClose: () => void }) { const [label, setLabel] = useState(''); const [amount, setAmount] = useState(''); const [payer, setPayer] = useState('Me'); const [category, setCategory] = useState('other'); return <Modal title="Add an expense" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSubmit({ tripId, label, amount: Number(amount), payer, category }) }} className="space-y-3"><input className="field" value={label} onChange={e => setLabel(e.target.value)} placeholder="What was it?" required /><input className="field" value={amount} onChange={e => setAmount(e.target.value)} placeholder="Amount" type="number" min="1" step="0.01" required /><input className="field" value={payer} onChange={e => setPayer(e.target.value)} placeholder="Paid by" required /><select className="field" value={category} onChange={e => setCategory(e.target.value)}><option>other</option><option>stay</option><option>food</option><option>transport</option><option>activities</option></select><button className="w-full rounded-xl bg-brand px-4 py-3 font-semibold text-brand-foreground">Save expense</button></form></Modal> }
function MemberForm({ tripId, onSubmit, onClose }: { tripId: string; onSubmit: (value: MemberInput) => void; onClose: () => void }) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); return <Modal title="Invite a traveler" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSubmit({ tripId, name, email }) }} className="space-y-3"><input className="field" value={name} onChange={e => setName(e.target.value)} placeholder="Name" required /><input className="field" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" type="email" required /><button className="w-full rounded-xl bg-brand px-4 py-3 font-semibold text-brand-foreground"><Send className="mr-2 inline" size={15} />Invite</button></form></Modal> }
function PlaceForm({ tripId, onSubmit, onClose }: { tripId: string; onSubmit: (value: PlaceInput) => void; onClose: () => void }) { const [name, setName] = useState(''); const [city, setCity] = useState(''); const [note, setNote] = useState(''); return <Modal title="Save a place" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSubmit({ tripId, name, city, note }) }} className="space-y-3"><input className="field" value={name} onChange={e => setName(e.target.value)} placeholder="Place name" required /><input className="field" value={city} onChange={e => setCity(e.target.value)} placeholder="City or area" required /><input className="field" value={note} onChange={e => setNote(e.target.value)} placeholder="Why save it?" /><button className="w-full rounded-xl bg-brand px-4 py-3 font-semibold text-brand-foreground">Save place</button></form></Modal> }
function Modal({ title, onClose, children }: any) { return <div className="mt-6 rounded-2xl border border-brand/30 bg-background p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">{title}</h3><button onClick={onClose} className="text-sm text-muted-foreground">Close</button></div>{children}</div> }

